apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-conf
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      root /usr/share/nginx/html;
      index index.html;

      # Serve the app under /koth
      location = /koth {
        try_files /index.html =404;
      }

      location /koth/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html =404;
      }
    }